warehouse = []
print("The list now: ",warehouse)
warehouse.extend(["Laptop", "Mouse", "Keyboard"])
print("The list now after adding new products: ",warehouse)
warehouse.append("Monitor")
print("The list now after inserting urgent product: ",warehouse)
new_products= ["Tablet", "Webcam"]
print("The products from another warehouse:",new_products)
warehouse.extend(new_products)
print("The list now after combining products from another warehouse: ",warehouse)
warehouse.remove("Mouse")
print("The list now after discontinuing a product: ",warehouse)
warehouse.remove("Webcam")
print("The list now after shipping a product: ",warehouse)
print("Counting occurence of laptop: ", warehouse.count("Laptop"))
print("Finding Monitor's location in list: ", warehouse.index("Monitor"))
warehouse.sort()
print("The list now after sorting: ",warehouse)
warehouse.reverse()
print("The list now after reversing: ",warehouse)
backup = warehouse.copy()
print("The backup of original list: ", backup)
backup.clear()
print("The temporary inventory after clearing: ", backup)
print("The list now:", warehouse)